spring:
  config:
    activate:
      on-profile: local
  redis:
    host: 127.0.0.1
    port: 6379
sms:
  serviceid: ncp:sms:kr:282615511747:validation_sms
  secretkey: Lf4Oqy1Ebsn9ecds1XC6RopnLodw9NG4z2b3EKLC
  accesskey: oekTboQ7Jao7JPzE8omf



